name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Build, Test & Coverage
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.10.2
          arguments: clean test jacocoTestReport --stacktrace

      - name: Upload unit test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            build/test-results
            build/reports/tests

      - name: Upload JaCoCo coverage report (HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html
